controller_manager:
  ros__parameters:
    update_rate: 50

    joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50

    arm_controller:
      type: position_controllers/JointTrajectoryController
      joints:
        - joint1
        - joint2
      state_publish_rate: 25
      action_monitor_rate: 10
      constraints:
        goal_time: 1.0
        stopped_velocity_tolerance: 0.01
      stop_trajectory_duration: 0.5
      allow_partial_joints_goal: true

  
