controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50

    arm_controller:
      type: position_controllers/JointTrajectoryController
      joints:
        - joint1
        - joint2
      state_publish_rate: 25
      action_monitor_rate: 10
      constraints:
        goal_time: 1.0
        stopped_velocity_tolerance: 0.02
        joint1:
          trajectory: 0.1
          goal: 0.1
        joint2:
          trajectory: 0.1
          goal: 0.1
      stop_trajectory_duration: 0.5
      state_publish_rate: 25
      action_monitor_rate: 10

    ros2_control:
      hardware_interface: gazebo_ros2_control/GazeboSystem
      joints:
        - name: joint1
          command_interfaces:
            - position
          state_interfaces:
            - position
            - velocity
        - name: joint2
          command_interfaces:
            - position
          state_interfaces:
            - position
            - velocity
